{{- if and .Values.cloudEventsPlayer.enabled .Values.cloudEventsPlayer.service.create .Values.cloudEventsPlayer.ingress.enabled }}
{{- $name := .Values.cloudEventsPlayer.name }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
  {{- with .Values.cloudEventsPlayer.ingress.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.cloudEventsPlayer.ingress.className }}
  ingressClassName: {{ .Values.cloudEventsPlayer.ingress.className }}
  {{- end }}
  {{- with .Values.cloudEventsPlayer.ingress.tls }}
  tls:
{{ toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range $host := .Values.cloudEventsPlayer.ingress.hosts }}
    - host: {{ $host.host | quote }}
      http:
        paths:
          {{- $paths := $host.paths | default (list (dict "path" "/" "pathType" "Prefix")) }}
          {{- range $path := $paths }}
          - path: {{ $path.path | quote }}
            pathType: {{ $path.pathType }}
            backend:
              service:
                name: {{ $name }}
                port:
                  number: {{ $.Values.cloudEventsPlayer.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
