{{- if .Values.emailer.install }}
{{- if or .Values.emailer.config.yagmailUser .Values.emailer.config.yagmailPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-emailer
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: na-emailer
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  {{- if .Values.emailer.config.yagmailUser }}
  NA_YAGMAIL_USER: {{ .Values.emailer.config.yagmailUser | quote }}
  {{- end }}
  {{- if .Values.emailer.config.yagmailPassword }}
  NA_YAGMAIL_PASSWORD: {{ .Values.emailer.config.yagmailPassword | quote }}
  {{- end }}
{{- end }}
{{- end }}
